sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - # PyLint does not yet support Python 3.6 https://github.com/PyCQA/pylint/issues/1241
    if [ "$TRAVIS_PYTHON_VERSION" != "3.6" ]; then
      pylint adal;
    fi
  - python -m unittest discover -s tests

deploy:
  - # test pypi
    provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "nugetaad"
    password:
      secure: "encrypted-password-string"
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

  - # production pypi
    provider: pypi
    distributions: sdist
    user: "nugetaad"
    password:
      secure: "encrypted-password-string"
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

